added templates

diff --git a/templates/kops/aws_launch_configuration_master_user_data.tmpl b/templates/kops/aws_launch_configuration_master_user_data.tmpl
--- a/templates/kops/aws_launch_configuration_master_user_data.tmpl
+++ b/templates/kops/aws_launch_configuration_master_user_data.tmpl
@@ -33,8 +33,8 @@ function ensure-install-dir() {
   if [[ -d /var/lib/toolbox ]]; then
     INSTALL_DIR="/var/lib/toolbox/kubernetes-install"
   fi
-  mkdir -p ${INSTALL_DIR}
-  cd ${INSTALL_DIR}
+  mkdir -p $${INSTALL_DIR}
+  cd $${INSTALL_DIR}
 }
 
 # Retry a download until we get it. args: name, sha, url1, url2...
@@ -45,33 +45,33 @@ download-or-bust() {
 
   urls=( $* )
   while true; do
-    for url in "${urls[@]}"; do
-      if [[ -e "${file}" ]]; then
-        echo "== File exists for ${url} =="
+    for url in "$${urls[@]}"; do
+      if [[ -e "$${file}" ]]; then
+        echo "== File exists for $${url} =="
 
       # CoreOS runs this script in a container without which (but has curl)
       # Note also that busybox wget doesn't support wget --version, but busybox doesn't normally have curl
       # So we default to wget unless we see curl
       elif [[ $(curl --version) ]]; then
-        if ! curl -f --ipv4 -Lo "${file}" --connect-timeout 20 --retry 6 --retry-delay 10 "${url}"; then
-          echo "== Failed to curl ${url}. Retrying. =="
+        if ! curl -f --ipv4 -Lo "$${file}" --connect-timeout 20 --retry 6 --retry-delay 10 "$${url}"; then
+          echo "== Failed to curl $${url}. Retrying. =="
           continue
         fi
       else
-        if ! wget --inet4-only -O "${file}" --connect-timeout=20 --tries=6 --wait=10 "${url}"; then
-          echo "== Failed to wget ${url}. Retrying. =="
+        if ! wget --inet4-only -O "$${file}" --connect-timeout=20 --tries=6 --wait=10 "$${url}"; then
+          echo "== Failed to wget $${url}. Retrying. =="
           continue
         fi
       fi
 
-      if [[ -n "${hash}" ]] && ! validate-hash "${file}" "${hash}"; then
-        echo "== Hash validation of ${url} failed. Retrying. =="
-        rm -f "${file}"
+      if [[ -n "$${hash}" ]] && ! validate-hash "$${file}" "$${hash}"; then
+        echo "== Hash validation of $${url} failed. Retrying. =="
+        rm -f "$${file}"
       else
-        if [[ -n "${hash}" ]]; then
-          echo "== Downloaded ${url} (SHA1 = ${hash}) =="
+        if [[ -n "$${hash}" ]]; then
+          echo "== Downloaded $${url} (SHA1 = $${hash}) =="
         else
-          echo "== Downloaded ${url} =="
+          echo "== Downloaded $${url} =="
         fi
         return
       fi
@@ -87,9 +87,9 @@ validate-hash() {
   local -r expected="$2"
   local actual
 
-  actual=$(sha256sum ${file} | awk '{ print $1 }') || true
-  if [[ "${actual}" != "${expected}" ]]; then
-    echo "== ${file} corrupted, hash ${actual} doesn't match expected ${expected} =="
+  actual=$(sha256sum $${file} | awk '{ print $1 }') || true
+  if [[ "$${actual}" != "$${expected}" ]]; then
+    echo "== $${file} corrupted, hash $${actual} doesn't match expected $${expected} =="
     return 1
   fi
 }
@@ -102,18 +102,18 @@ function try-download-release() {
   # TODO(zmerlynn): Now we REALLY have no excuse not to do the reboot
   # optimization.
 
-  local -r nodeup_urls=( $(split-commas "${NODEUP_URL}") )
-  if [[ -n "${NODEUP_HASH:-}" ]]; then
-    local -r nodeup_hash="${NODEUP_HASH}"
+  local -r nodeup_urls=( $(split-commas "$${NODEUP_URL}") )
+  if [[ -n "$${NODEUP_HASH:-}" ]]; then
+    local -r nodeup_hash="$${NODEUP_HASH}"
   else
   # TODO: Remove?
     echo "Downloading sha256 (not found in env)"
-    download-or-bust nodeup.sha256 "" "${nodeup_urls[@]/%/.sha256}"
+    download-or-bust nodeup.sha256 "" "$${nodeup_urls[@]/%/.sha256}"
     local -r nodeup_hash=$(cat nodeup.sha256)
   fi
 
-  echo "Downloading nodeup (${nodeup_urls[@]})"
-  download-or-bust nodeup "${nodeup_hash}" "${nodeup_urls[@]}"
+  echo "Downloading nodeup ($${nodeup_urls[@]})"
+  download-or-bust nodeup "$${nodeup_hash}" "$${nodeup_urls[@]}"
 
   chmod +x nodeup
 }
@@ -127,7 +127,7 @@ function download-release() {
 
   echo "Running nodeup"
   # We can't run in the foreground because of https://github.com/docker/docker/issues/23793
-  ( cd ${INSTALL_DIR}; ./nodeup --install-systemd-unit --conf=${INSTALL_DIR}/kube_env.yaml --v=8  )
+  ( cd $${INSTALL_DIR}; ./nodeup --install-systemd-unit --conf=$${INSTALL_DIR}/kube_env.yaml --v=8  )
 }
 
 ####################################################################################
@@ -207,7 +207,7 @@ kubeControllerManager:
   attachDetachReconcileSyncPeriod: 1m0s
   cloudProvider: aws
   clusterCIDR: 100.96.0.0/11
-  clusterName: dev.barath-devops.com
+  clusterName: ${cluster_name}
   configureCloudRoutes: false
   image: k8s.gcr.io/kube-controller-manager:v1.15.4
   leaderElection:
@@ -277,17 +277,17 @@ Assets:
 - ada48ed9160f83bda949546fd2c7e443b97a5212c4f99148d66866c65ceb9dab@https://storage.googleapis.com/kubernetes-release/release/v1.15.4/bin/linux/amd64/kubectl
 - 3ca15c0a18ee830520cf3a95408be826cbd255a1535a38e0be9608b25ad8bf64@https://storage.googleapis.com/kubernetes-release/network-plugins/cni-plugins-amd64-v0.7.5.tgz
 - af89c1d1a4ed0328ec4bf534f0919de3fc00706d9bf227ff89fe7c748e6e6cd6@https://artifacts.k8s.io/binaries/kops/1.15.0-beta.1/linux/amd64/utils.tar.gz,https://github.com/kubernetes/kops/releases/download/1.15.0-beta.1/linux-amd64-utils.tar.gz,https://kubeupv2.s3.amazonaws.com/kops/1.15.0-beta.1/linux/amd64/utils.tar.gz
-ClusterName: dev.barath-devops.com
-ConfigBase: s3://kops-us-east-1-barath-bucket/dev.barath-devops.com
+ClusterName: ${cluster_name}
+ConfigBase: s3://${bucket_name}/${cluster_name}
 InstanceGroupName: master-us-east-1a
 Tags:
 - _automatic_upgrades
 - _aws
 channels:
-- s3://kops-us-east-1-barath-bucket/dev.barath-devops.com/addons/bootstrap-channel.yaml
+- s3://${bucket_name}/${cluster_name}/addons/bootstrap-channel.yaml
 etcdManifests:
-- s3://kops-us-east-1-barath-bucket/dev.barath-devops.com/manifests/etcd/main.yaml
-- s3://kops-us-east-1-barath-bucket/dev.barath-devops.com/manifests/etcd/events.yaml
+- s3://${bucket_name}/${cluster_name}/manifests/etcd/main.yaml
+- s3://${bucket_name}/${cluster_name}/manifests/etcd/events.yaml
 protokubeImage:
   hash: 44a8a85e5f2bd31c52e1232670107bbb3a720b8ff1602ed3e24b1e4e56cb03af
   name: protokube:1.15.0-beta.1
